### PR TITLE
Master

### PR DESCRIPTION
**Pull request by chironmartini**

### CODE REVIEW

**Comment by sleepinghungry** [comment]
Resolved.  However, I still think you might want to revert this merge.  The changes are pretty drastic.  I think the only code that should be merged is the port to python 3.5.2.

**Comment by sleepinghungry** [comment]
Hi there.  It just occurred me to that you merged the code as a result of a pull request.  Except I didn't initiate one--it looks like one of my students initiated it by accident.  I'm so sorry.  I recommend reverting the merge, and with your permission, I'll do it.

**Comment by gever** [comment]
Hmm, guess I should have looked at it more closely.  I'll just go ahead and give you permission to help manage pull requests.

**Comment by sleepinghungry** [comment]
Thanks!  Reverting now.

**Pull request merged**
